#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xBB5869F064EA74AB (chet@cwru.edu)
#
%define keepstatic 1
Name     : compat-readline
Version  : 6.3
Release  : 44
URL      : http://mirrors.kernel.org/gnu/readline/readline-6.3.tar.gz
Source0  : http://mirrors.kernel.org/gnu/readline/readline-6.3.tar.gz
Source1 : http://mirrors.kernel.org/gnu/readline/readline-6.3.tar.gz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: compat-readline-lib = %{version}-%{release}
Requires: compat-readline-license = %{version}-%{release}
BuildRequires : ncurses-dev
# Suppress generation of debuginfo
%global debug_package %{nil}
Patch1: readline63-001
Patch2: readline63-002
Patch3: readline63-003
Patch4: readline63-004
Patch5: readline63-005
Patch6: readline63-006
Patch7: readline63-007
Patch8: readline63-008
Patch9: 0001-Defaultinput-meta-output-meta-to-on.patch
Patch10: cve-2014-2524.nopatch
Patch11: 0001-Support-stateless-inputrc-configuration.patch
Patch12: build.patch
Patch13: readline-6.2-shlib.patch

%description
Introduction
============
This is the Gnu Readline library, version 6.3.
The Readline library provides a set of functions for use by applications
that allow users to edit command lines as they are typed in.  Both
Emacs and vi editing modes are available.  The Readline library includes
additional functions to maintain a list of previously-entered command
lines, to recall and perhaps reedit those lines, and perform csh-like
history expansion on previous commands.

%package lib
Summary: lib components for the compat-readline package.
Group: Libraries
Requires: compat-readline-license = %{version}-%{release}

%description lib
lib components for the compat-readline package.


%package license
Summary: license components for the compat-readline package.
Group: Default

%description license
license components for the compat-readline package.


%prep
%setup -q -n readline-6.3
%patch1 -p0
%patch2 -p0
%patch3 -p0
%patch4 -p0
%patch5 -p0
%patch6 -p0
%patch7 -p0
%patch8 -p0
%patch9 -p1
%patch11 -p1
%patch12 -p1
%patch13 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568240863
unset LD_AS_NEEDED
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
%configure  --with-curses
make  %{?_smp_mflags} SHLIB_LIBS="-ltinfo"

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1568240863
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-readline
cp COPYING %{buildroot}/usr/share/package-licenses/compat-readline/COPYING
%make_install
## Remove excluded files
rm -f %{buildroot}/usr/include/readline/chardefs.h
rm -f %{buildroot}/usr/include/readline/history.h
rm -f %{buildroot}/usr/include/readline/keymaps.h
rm -f %{buildroot}/usr/include/readline/readline.h
rm -f %{buildroot}/usr/include/readline/rlconf.h
rm -f %{buildroot}/usr/include/readline/rlstdc.h
rm -f %{buildroot}/usr/include/readline/rltypedefs.h
rm -f %{buildroot}/usr/include/readline/tilde.h
rm -f %{buildroot}/usr/lib64/libhistory.a
rm -f %{buildroot}/usr/lib64/libhistory.so
rm -f %{buildroot}/usr/lib64/libreadline.a
rm -f %{buildroot}/usr/lib64/libreadline.so
rm -f %{buildroot}/usr/share/doc/readline/CHANGES
rm -f %{buildroot}/usr/share/doc/readline/INSTALL
rm -f %{buildroot}/usr/share/doc/readline/README
rm -f %{buildroot}/usr/share/info/history.info
rm -f %{buildroot}/usr/share/info/readline.info
rm -f %{buildroot}/usr/share/info/rluserman.info
rm -f %{buildroot}/usr/share/man/man3/history.3
rm -f %{buildroot}/usr/share/man/man3/readline.3
rm -f %{buildroot}/usr/share/readline/excallback.c
rm -f %{buildroot}/usr/share/readline/fileman.c
rm -f %{buildroot}/usr/share/readline/hist_erasedups.c
rm -f %{buildroot}/usr/share/readline/hist_purgecmd.c
rm -f %{buildroot}/usr/share/readline/histexamp.c
rm -f %{buildroot}/usr/share/readline/manexamp.c
rm -f %{buildroot}/usr/share/readline/rl-callbacktest.c
rm -f %{buildroot}/usr/share/readline/rl-fgets.c
rm -f %{buildroot}/usr/share/readline/rl.c
rm -f %{buildroot}/usr/share/readline/rlcat.c
rm -f %{buildroot}/usr/share/readline/rlevent.c
rm -f %{buildroot}/usr/share/readline/rlptytest.c
rm -f %{buildroot}/usr/share/readline/rltest.c
rm -f %{buildroot}/usr/share/readline/rlversion.c

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/libhistory.so.6
/usr/lib64/libhistory.so.6.3
/usr/lib64/libreadline.so.6
/usr/lib64/libreadline.so.6.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-readline/COPYING
