#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : compat-readline
Version  : 6.3
Release  : 41
URL      : http://mirrors.kernel.org/gnu/readline/readline-6.3.tar.gz
Source0  : http://mirrors.kernel.org/gnu/readline/readline-6.3.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: compat-readline-data = %{version}-%{release}
Requires: compat-readline-lib = %{version}-%{release}
Requires: compat-readline-license = %{version}-%{release}
BuildRequires : ncurses-dev
Patch1: readline63-001
Patch2: readline63-002
Patch3: readline63-003
Patch4: readline63-004
Patch5: readline63-005
Patch6: readline63-006
Patch7: readline63-007
Patch8: readline63-008
Patch9: 0001-Defaultinput-meta-output-meta-to-on.patch
Patch10: cve-2014-2524.nopatch
Patch11: 0001-Support-stateless-inputrc-configuration.patch
Patch12: build.patch
Patch13: readline-6.2-shlib.patch

%description
Introduction
============
This is the Gnu Readline library, version 6.3.
The Readline library provides a set of functions for use by applications
that allow users to edit command lines as they are typed in.  Both
Emacs and vi editing modes are available.  The Readline library includes
additional functions to maintain a list of previously-entered command
lines, to recall and perhaps reedit those lines, and perform csh-like
history expansion on previous commands.

%package data
Summary: data components for the compat-readline package.
Group: Data

%description data
data components for the compat-readline package.


%package dev
Summary: dev components for the compat-readline package.
Group: Development
Requires: compat-readline-lib = %{version}-%{release}
Requires: compat-readline-data = %{version}-%{release}
Provides: compat-readline-devel = %{version}-%{release}
Requires: compat-readline = %{version}-%{release}

%description dev
dev components for the compat-readline package.


%package doc
Summary: doc components for the compat-readline package.
Group: Documentation

%description doc
doc components for the compat-readline package.


%package lib
Summary: lib components for the compat-readline package.
Group: Libraries
Requires: compat-readline-data = %{version}-%{release}
Requires: compat-readline-license = %{version}-%{release}

%description lib
lib components for the compat-readline package.


%package license
Summary: license components for the compat-readline package.
Group: Default

%description license
license components for the compat-readline package.


%package staticdev
Summary: staticdev components for the compat-readline package.
Group: Default
Requires: compat-readline-dev = %{version}-%{release}

%description staticdev
staticdev components for the compat-readline package.


%prep
%setup -q -n readline-6.3
%patch1 -p0
%patch2 -p0
%patch3 -p0
%patch4 -p0
%patch5 -p0
%patch6 -p0
%patch7 -p0
%patch8 -p0
%patch9 -p1
%patch11 -p1
%patch12 -p1
%patch13 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1567788842
unset LD_AS_NEEDED
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
%configure  --with-curses
make  %{?_smp_mflags} SHLIB_LIBS="-ltinfo"

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1567788842
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-readline
cp COPYING %{buildroot}/usr/share/package-licenses/compat-readline/COPYING
%make_install
## install_append content
rm %{buildroot}/usr/lib64/libreadline.so
echo "INPUT(libreadline.so.6 -ltinfow)" > %{buildroot}/usr/lib64/libreadline.so
chmod 755 %{buildroot}/usr/lib64/*
## install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/readline/excallback.c
/usr/share/readline/fileman.c
/usr/share/readline/hist_erasedups.c
/usr/share/readline/hist_purgecmd.c
/usr/share/readline/histexamp.c
/usr/share/readline/manexamp.c
/usr/share/readline/rl-callbacktest.c
/usr/share/readline/rl-fgets.c
/usr/share/readline/rl.c
/usr/share/readline/rlcat.c
/usr/share/readline/rlevent.c
/usr/share/readline/rlptytest.c
/usr/share/readline/rltest.c
/usr/share/readline/rlversion.c

%files dev
%defattr(-,root,root,-)
/usr/include/readline/chardefs.h
/usr/include/readline/history.h
/usr/include/readline/keymaps.h
/usr/include/readline/readline.h
/usr/include/readline/rlconf.h
/usr/include/readline/rlstdc.h
/usr/include/readline/rltypedefs.h
/usr/include/readline/tilde.h
/usr/lib64/libhistory.so
/usr/lib64/libreadline.so
/usr/share/man/man3/history.3
/usr/share/man/man3/readline.3

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/info/*
/usr/share/doc/readline/CHANGES
/usr/share/doc/readline/INSTALL
/usr/share/doc/readline/README

%files lib
%defattr(-,root,root,-)
/usr/lib64/libhistory.so.6
/usr/lib64/libhistory.so.6.3
/usr/lib64/libreadline.so.6
/usr/lib64/libreadline.so.6.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-readline/COPYING

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/libhistory.a
/usr/lib64/libreadline.a
